language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
env:
  - DB=mysql
gemfile:
  - Gemfile
  - ci/gemfiles/rspec2_8_rails3_1.gemfile
  - ci/gemfiles/rspec2_8_rails3_0.gemfile
  - ci/gemfiles/rspec2_7_rails3_2.gemfile
before_script:
  - "mysql -e 'create database `foreigner-matcher_test`;'"
  - bundle exec rake db:test:reset --trace
script: bundle exec rspec -b
