language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
env:
  - DB=mysql
  - DB=postgres
before_script:
  - "mysql -e 'create database foreigner-matcher_test;'"
  - "psql -c 'create database foreigner-matcher_test;' -U postgres"
  - bundle exec rake db:test:reset
script: bundle exec rspec spec
